version: "3"

services:
  server:
    container_name: rpm-ostree-compose
    image: flexo3001/rpm-ostree-compose:latest
    #build:
    #  context: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    privileged: true
    network_mode: "bridge"
    security_opt:
      - label:disable
